name: dacapo-testing

on: [pull_request]

jobs:
  dacapo-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Version
        run: |
          cat /etc/os-release
          php -v
          composer --version

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Execute tests via PHPUnit
        run: |
          composer test
