name: php-cs-fixer

on:
  push:
    branches: [v4.0]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: php-cs-version
        run: |
          make php-cs-version
          make php-cs-dry
